import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import ContactMe from '../components/ContactMe'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Projects from '../components/Projects/Projects'
import Skills from '../components/Skills/Skills'


const Home = () => {

  return (<>
    <Head>
      <title>Dmitriy&apos;s Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <base target="_blank" />
    </Head>
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]/80'>


      <Header />

      <section id='hero' className='snap-start'>
        <Hero />
      </section>

      <section id='about' className='snap-center'>
        <About />
      </section>

      {/* <section id='experience' className='snap-center'>
        <WorkExperience experiences={experiences} />
      </section> */}

      <section id='skills' className='snap-start'>
        <Skills />
      </section>

      <section id='projects' className='snap-start'>
        <Projects />
      </section>

      <section id='contact' className='snap-start'>
        <ContactMe />
      </section>

      <Link href='#hero'>
        <footer className='sticky bottom-2 w-full cursor-pointer'>
          <div className='flex items-center justify-center mx-auto'>
            <Image
              width={40}
              height={40}
              className='opacity-30 rounded-full filter cursor-pointer
              hover:opacity-100'
              src='Icons/arrow-up.svg' alt='arrow up' />
          </div>
        </footer>
      </Link>
    </div>
  </>
  )
}
export default Home;
